[
  ["current_item", "STRING"],
  ["add_purchase", "CODE"],
  ["buttons_category", "HASHMAP"],
  ["description_frame", "CONTROL"],
  ["selected_items", "ARRAY"],
  ["display", "DISPLAY"],
  ["item_model_3d", "OBJECT"],
  ["render_item", "CODE"],
  ["updt_product_list", "CODE"],
  ["cancel_button", "CONTROL"],
  ["camera", "OBJECT"],
  ["close_shop", "CODE"],
  ["list_boxes", "HASHMAP"],
  ["description_box", "CONTROL"],
  ["trade_price", "SCALAR"],
  ["remove_purchase", "CODE"],
  ["inventory", "HASHMAP"],
  ["desk", "OBJECT"],
  ["total_trade_cost", "CODE"],
  ["update_trade_frame", "CODE"],
  ["category", "STRING"],
  ["clear_button", "CONTROL"],
  ["update_description", "CODE"],
];
