#include "config\cfgPatches.cpp"
#include "config\cfgFunctions.cpp"
#include "config\cfgVehicles.cpp"
#include "config\cfgWeapons.cpp"
#include "config\cfgMagazines.cpp"
#include "config\preInitEvents.cpp"